import sys
sys.path.insert(0, "../")
import chromewhip.protocol.console
import chromewhip.protocol.debugger
import chromewhip.protocol.heapprofiler
import chromewhip.protocol.profiler
import chromewhip.protocol.runtime
import chromewhip.protocol.schema
import chromewhip.protocol.accessibility
import chromewhip.protocol.animation
import chromewhip.protocol.applicationcache
import chromewhip.protocol.audits
import chromewhip.protocol.backgroundservice
import chromewhip.protocol.browser
import chromewhip.protocol.css
import chromewhip.protocol.cachestorage
import chromewhip.protocol.cast
import chromewhip.protocol.dom
import chromewhip.protocol.domdebugger
import chromewhip.protocol.domsnapshot
import chromewhip.protocol.domstorage
import chromewhip.protocol.database
import chromewhip.protocol.deviceorientation
import chromewhip.protocol.emulation
import chromewhip.protocol.headlessexperimental
import chromewhip.protocol.io
import chromewhip.protocol.indexeddb
import chromewhip.protocol.input
import chromewhip.protocol.inspector
import chromewhip.protocol.layertree
import chromewhip.protocol.log
import chromewhip.protocol.memory
import chromewhip.protocol.network
import chromewhip.protocol.overlay
import chromewhip.protocol.page
import chromewhip.protocol.performance
import chromewhip.protocol.security
import chromewhip.protocol.serviceworker
import chromewhip.protocol.storage
import chromewhip.protocol.systeminfo
import chromewhip.protocol.target
import chromewhip.protocol.tethering
import chromewhip.protocol.tracing
import chromewhip.protocol.fetch
import chromewhip.protocol.webaudio
import chromewhip.protocol.webauthn
import chromewhip.protocol.media
